#!bin/bash
echo " enter username:"
read name
echo " enter password:"
read ps
#n="admin"
#p="testyantra123"
if [ $name =="admin" -a  $ps =="testyantra123" ]
then 
   echo " Authentication successfull "
else
   echo " unsuccessfull "
fi

